___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

# Data Frames

 - ### ``DataFrames`` are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [1]:
import pandas as pd
import numpy as np

 - ### Creating a DataFrame using the ``list``s of data and columns

In [2]:
data = [1, 2, 39, 67, 90] 

In [3]:
data

[1, 2, 39, 67, 90]

In [4]:
pd.DataFrame(data, columns = ["column_name"])

column_name
0            1
1            2
2           39
3           67
4           90

 - ### Creating a DataFrame using a ``NumPy Arrays``

In [5]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
pd.DataFrame(m,columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [7]:
pd.DataFrame(columns = ["var1","var2","var3"],data = m)

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [8]:
df = pd.DataFrame(data = m,columns = ["var1","var2","var3"])
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [9]:
df.head(2)

var1  var2  var3
0     1     2     3
1     4     5     6

In [11]:
df.tail(1)

var1  var2  var3
2     7     8     9

In [12]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [13]:
df.columns = ["new1","new2","new3"]


In [14]:
df

new1  new2  new3
0     1     2     3
1     4     5     6
2     7     8     9

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.shape

(3, 3)

In [17]:
df.ndim

2

In [18]:
df.size

9

In [20]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
df.index

RangeIndex(start=0, stop=3, step=1)

 - ### Creating a DataFrame using a ``dict``

In [22]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [23]:
s1

array([3, 1, 2, 5, 0])

In [24]:
s2

array([7, 3, 0, 4, 3])

In [25]:
s3

array([4, 3, 2, 7, 9])

In [26]:
myDict = {"var1":s1,"var2":s2,"var3":s3}
myDict

{'var1': array([3, 1, 2, 5, 0]),
 'var2': array([7, 3, 0, 4, 3]),
 'var3': array([4, 3, 2, 7, 9])}

In [28]:
df1 = pd.DataFrame(myDict)
df1

var1  var2  var3
0     3     7     4
1     1     3     3
2     2     0     2
3     5     4     7
4     0     3     9

In [29]:
df1[1:3] # calls rowwise 

var1  var2  var3
1     1     3     3
2     2     0     2

In [30]:
df1.index = [i for i in "kübra"]

In [31]:
df1

var1  var2  var3
k     3     7     4
ü     1     3     3
b     2     0     2
r     5     4     7
a     0     3     9

In [32]:
df1[1:4]

var1  var2  var3
ü     1     3     3
b     2     0     2
r     5     4     7

In [33]:
df1["ü":"r"] # both inclusive

var1  var2  var3
ü     1     3     3
b     2     0     2
r     5     4     7

In [34]:
df1["k"] # what is the output?

KeyError: 'k'

In [ ]:
# I can handle that with this kind of syntax

In [33]:
#@title
df1[:"t"] 

var1  var2  var3
t     1     1     4

In [35]:
"var2" in df1 # columwise

True

In [37]:
"k" in df1

False

In [38]:
2 in df1.values

True

In [40]:
9 in df1[:"k"].values

False

### Now, let's examine again the ***indexing, selection*** and ***slicing*** methods and several ***attributes*** using a different DataFrame

In [41]:
import numpy as np
import pandas as pd

In [42]:
np.random.seed(101)
idx = np.random.choice([i for i in "uncopyrightable".upper()],size=5,replace=False)
cols = np.random.choice([i for i in "dermatoglyphics".upper()],size=4,replace=False)

df3 = pd.DataFrame((np.random.randn(5,4).round(2)),index = idx, columns = cols)

df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
O -1.33  2.08  1.75 -0.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [43]:
df3['A']

L    0.56
C    1.28
O   -1.33
B    0.71
T   -0.15
Name: A, dtype: float64

In [44]:
type(df3['A'])

pandas.core.series.Series

In [45]:
df3[['A']]

A
L  0.56
C  1.28
O -1.33
B  0.71
T -0.15

In [46]:
type(df3[['A']])

pandas.core.frame.DataFrame

In [47]:
df3[['A','G']]

A     G
L  0.56  1.40
C  1.28  0.31
O -1.33  1.75
B  0.71  0.94
T -0.15  0.39

In [48]:
df3.A

L    0.56
C    1.28
O   -1.33
B    0.71
T   -0.15
Name: A, dtype: float64

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [49]:
df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
O -1.33  2.08  1.75 -0.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [50]:
df3["O" : "B"]

A     H     G     D
O -1.33  2.08  1.75 -0.06
B  0.71 -1.08  0.94  1.30

In [51]:
df3[:"L"] # ? 

A     H    G     D
L  0.56  0.14  1.4 -0.32

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 4</p><h1>
    <h2><p style="text-align: center;">Part - 1</p><h2>

**Creating a new column:**

In [51]:
df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
O -1.33  2.08  1.75 -0.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [52]:
df3["AHmax"] = (df3['A'] + df3['H']).max()

df3

A     H     G     D  AHmax
L  0.56  0.14  1.40 -0.32   1.11
C  1.28 -0.17  0.31 -1.06   1.11
O -1.33  2.08  1.75 -0.06   1.11
B  0.71 -1.08  0.94  1.30   1.11
T -0.15  0.14  0.39  0.32   1.11

### [Removing Columns & Rows](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-drop.ipynb)

 - ### Removing Columns

In [55]:
df3.drop('AHmax', axis = 1)

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
O -1.33  2.08  1.75 -0.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [56]:
df3

A     H     G     D  AHmax
L  0.56  0.14  1.40 -0.32   1.11
C  1.28 -0.17  0.31 -1.06   1.11
O -1.33  2.08  1.75 -0.06   1.11
B  0.71 -1.08  0.94  1.30   1.11
T -0.15  0.14  0.39  0.32   1.11

In [57]:
df3 = df3.drop('AHmax', axis = 1, inplace = True)

In [ ]:
df3 = df3.drop('AHmax', axis = 1)

In [58]:
df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
O -1.33  2.08  1.75 -0.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

 - ### Removing rows

In [59]:
df3.drop('O',axis = 0)

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [60]:
df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
O -1.33  2.08  1.75 -0.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [61]:
df3.drop('O',axis = 0,inplace = True)

In [62]:
df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

### Selecting Rows

- ### First, let's take a quick look at [`.loc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-loc.ipynb) | [`.iloc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-iloc.ipynb)

#### `.loc[]` → allows us to select data using **labels** (names) of rows (index) & columns

#### `.iloc[]` → allows us to select data using **index numbers** of rows (index) & columns. it's like classical indexing logic

In [63]:
m = np.random.randint(1,30, size = (10,3))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df4

var1  var2  var3
0    20    19     4
1    11    20    29
2     8    21    28
3     9    23    27
4    27    20    24
5    15    16    23
6     6    23    10
7    14     3    19
8    27    16    29
9    12    28    11

In [64]:
df4.loc[6] # ?

var1     6
var2    23
var3    10
Name: 6, dtype: int32

In [65]:
df4.loc[2:4] # ? 

var1  var2  var3
2     8    21    28
3     9    23    27
4    27    20    24

In [66]:
df4.iloc[3:5] # ?

var1  var2  var3
3     9    23    27
4    27    20    24

In [67]:
df4.index = "a b c d e f g h i j".split()

In [68]:
df4

var1  var2  var3
a    20    19     4
b    11    20    29
c     8    21    28
d     9    23    27
e    27    20    24
f    15    16    23
g     6    23    10
h    14     3    19
i    27    16    29
j    12    28    11

In [69]:
df4.iloc[1:4]

var1  var2  var3
b    11    20    29
c     8    21    28
d     9    23    27

In [124]:
#df4.loc[1:4]

In [70]:
df4.loc["a" : "d"]

var1  var2  var3
a    20    19     4
b    11    20    29
c     8    21    28
d     9    23    27

In [72]:
df4

var1  var2  var3
a    20    19     4
b    11    20    29
c     8    21    28
d     9    23    27
e    27    20    24
f    15    16    23
g     6    23    10
h    14     3    19
i    27    16    29
j    12    28    11

In [73]:
df4.loc["f","var3"] # ?

23

In [70]:
df4.iloc[2,2] # ?

28

In [71]:
df4.loc["c":"f","var2"]

c    21
d    23
e    20
f    16
Name: var2, dtype: int32

In [72]:
df4["var2"][2:6]

c    21
d    23
e    20
f    16
Name: var2, dtype: int32

In [73]:
df4.iloc[2:6,1]

c    21
d    23
e    20
f    16
Name: var2, dtype: int32

In [74]:
df4.var2[2:6]

c    21
d    23
e    20
f    16
Name: var2, dtype: int32

In [75]:
df4.loc["c":"f"][["var2"]]

var2
c    21
d    23
e    20
f    16

In [76]:
type(df4.loc["c":"f"][["var2"]])

pandas.core.frame.DataFrame

#### Let's continue to examine `.loc[]` and `.iloc[]` using ``df3`` again

In [74]:
df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [75]:
df3.iloc[2]

A    0.71
H   -1.08
G    0.94
D    1.30
Name: B, dtype: float64

In [79]:
df3.iloc[[2]]

A     H     G    D
B  0.71 -1.08  0.94  1.3

### Selecting subset of rows and columns

 - ### `.loc[[row labels|names], [column labels|names]]`

 - ### `.iloc[[row index numbers], [column index numbers]]`

In [76]:
df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [77]:
df3.loc["B","D"]

1.3

In [82]:
df3.loc[["L"],["A"]] # value and type ?

A
L  0.56

In [78]:
df3.loc["L":"C","A":"H"] # value and type ?

A     H
L  0.56  0.14
C  1.28 -0.17

In [169]:
df3.iloc[0:2,0:2]

A     H
L  0.56  0.14
C  1.28 -0.17

In [170]:
type(df3.iloc[0:2,0:2])

pandas.core.frame.DataFrame

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [79]:
df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [80]:
df3 > 0

A      H     G      D
L   True   True  True  False
C   True  False  True  False
B   True  False  True   True
T  False   True  True   True

In [81]:
df3[df3 > 0]

A     H     G     D
L  0.56  0.14  1.40   NaN
C  1.28   NaN  0.31   NaN
B  0.71   NaN  0.94  1.30
T   NaN  0.14  0.39  0.32

In [82]:
df3[df3["A"] > 0]

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
B  0.71 -1.08  0.94  1.30

In [88]:
df3[df3["A"] > 0]["A"]

L    0.56
C    1.28
B    0.71
Name: A, dtype: float64

In [83]:
type(df3[df3["A"] > 0]["A"])

pandas.core.series.Series

In [84]:
df3[df3["A"] > 0][["A"]]

A
L  0.56
C  1.28
B  0.71

In [180]:
# I want you to create a dataframe slice where colunm A values greater than 0 
# the labels, column names must be in alpabetical order

In [ ]:
#@title
df3[df3["A"] > 0].loc[["B","C","L"],["G","H"]]

#### For two conditions you can use **|** → `or`,  **&** →  `and` with parenthesis:

In [91]:
df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [92]:
df3[(df3['A'] > 0) & (df3['D'] > 1)]

A     H     G    D
B  0.71 -1.08  0.94  1.3

In [93]:
df3[(df3['A'] > 0) | (df3['D'] > 1)]

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
B  0.71 -1.08  0.94  1.30

#### Conditional selection using ``.loc[]`` and ``.iloc[]``

In [188]:
#@title Question
df3.loc[(df3.A > 0),"A":"D"]

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
B  0.71 -1.08  0.94  1.30

In [ ]:
#@title
df3.loc[(df3.A > 0),:]

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [95]:
df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [96]:
df3.reset_index()

index     A     H     G     D
0     L  0.56  0.14  1.40 -0.32
1     C  1.28 -0.17  0.31 -1.06
2     B  0.71 -1.08  0.94  1.30
3     T -0.15  0.14  0.39  0.32

In [97]:
df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [98]:
df3.reset_index(drop = True)

A     H     G     D
0  0.56  0.14  1.40 -0.32
1  1.28 -0.17  0.31 -1.06
2  0.71 -1.08  0.94  1.30
3 -0.15  0.14  0.39  0.32

In [99]:
df3

A     H     G     D
L  0.56  0.14  1.40 -0.32
C  1.28 -0.17  0.31 -1.06
B  0.71 -1.08  0.94  1.30
T -0.15  0.14  0.39  0.32

In [100]:
df3.reset_index(drop = True,inplace = True)

In [101]:
df3

A     H     G     D
0  0.56  0.14  1.40 -0.32
1  1.28 -0.17  0.31 -1.06
2  0.71 -1.08  0.94  1.30
3 -0.15  0.14  0.39  0.32

In [106]:
newindx = 'CA NY WY OR'.split()

In [107]:
df3["States"] = newindx

In [108]:
df3

A     H     G     D States
0  0.56  0.14  1.40 -0.32     CA
1  1.28 -0.17  0.31 -1.06     NY
2  0.71 -1.08  0.94  1.30     WY
3 -0.15  0.14  0.39  0.32     OR

In [109]:
df3.set_index('States')

A     H     G     D
States                        
CA      0.56  0.14  1.40 -0.32
NY      1.28 -0.17  0.31 -1.06
WY      0.71 -1.08  0.94  1.30
OR     -0.15  0.14  0.39  0.32

In [110]:
df3

A     H     G     D States
0  0.56  0.14  1.40 -0.32     CA
1  1.28 -0.17  0.31 -1.06     NY
2  0.71 -1.08  0.94  1.30     WY
3 -0.15  0.14  0.39  0.32     OR

In [111]:
df3.set_index('States', inplace = True)

In [112]:
df3

A     H     G     D
States                        
CA      0.56  0.14  1.40 -0.32
NY      1.28 -0.17  0.31 -1.06
WY      0.71 -1.08  0.94  1.30
OR     -0.15  0.14  0.39  0.32

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [113]:
# Index Levels
outside = ['M1', 'M1', 'M1', 'M2', 'M2', 'M2']
inside = [1, 2, 3, 1, 2, 3]
multi_index = list(zip(outside, inside))
multi_index

[('M1', 1), ('M1', 2), ('M1', 3), ('M2', 1), ('M2', 2), ('M2', 3)]

In [114]:
hier_index = pd.MultiIndex.from_tuples(multi_index)
hier_index

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3)],
           )

In [115]:
df5 = pd.DataFrame(np.random.randn(6,2),index = hier_index, columns = ["A","B"])

df5

A         B
M1 1 -0.229937 -1.283599
   2 -2.711192 -1.522410
   3 -1.416207  1.108544
M2 1  1.131029  0.498600
   2  1.179022  1.322684
   3  1.852155 -0.892172

In [116]:
df5.loc["M1"]

A         B
1 -0.229937 -1.283599
2 -2.711192 -1.522410
3 -1.416207  1.108544

In [117]:
df5.loc["M1"].loc[[1]]

A         B
1 -0.229937 -1.283599

In [118]:
df5.index.names = ['Group','Number']

In [119]:
df5

A         B
Group Number                    
M1    1      -0.229937 -1.283599
      2      -2.711192 -1.522410
      3      -1.416207  1.108544
M2    1       1.131029  0.498600
      2       1.179022  1.322684
      3       1.852155 -0.892172

### let's take a quick look at the [``.xs()``](http://localhost:8888/notebooks/w3resource-pandas-dataframe-xs.ipynb)

In [120]:
df5.xs('M1')

A         B
Number                    
1      -0.229937 -1.283599
2      -2.711192 -1.522410
3      -1.416207  1.108544

In [121]:
df5.xs('M2')

A         B
Number                    
1       1.131029  0.498600
2       1.179022  1.322684
3       1.852155 -0.892172

In [122]:
df5.xs(["M1",1])

A   -0.229937
B   -1.283599
Name: (M1, 1), dtype: float64

In [123]:
df5.xs(("M1",1))

A   -0.229937
B   -1.283599
Name: (M1, 1), dtype: float64

In [225]:
# Group: M1  Number : 1 as DF? 
# hint: you can use .loc 

In [124]:
#@title 
df5.xs("M1").loc[[1]]

A         B
Number                    
1      -0.229937 -1.283599

In [125]:
df5.xs(("M1",1),level = [0,1])

A         B
Group Number                    
M1    1      -0.229937 -1.283599

In [126]:
df5

A         B
Group Number                    
M1    1      -0.229937 -1.283599
      2      -2.711192 -1.522410
      3      -1.416207  1.108544
M2    1       1.131029  0.498600
      2       1.179022  1.322684
      3       1.852155 -0.892172

In [128]:
df5.xs(1,level = "Number")

A         B
Group                    
M1    -0.229937 -1.283599
M2     1.131029  0.498600

In [129]:
df5.xs(1,level = 1 )

A         B
Group                    
M1    -0.229937 -1.283599
M2     1.131029  0.498600

In [130]:
df5.xs("A",axis=1)

Group  Number
M1     1        -0.229937
       2        -2.711192
       3        -1.416207
M2     1         1.131029
       2         1.179022
       3         1.852155
Name: A, dtype: float64

In [131]:
df5.xs("A",axis=1).loc["M1"].loc[1]

-0.22993749784225512

## melt(), unstack(), stack()

In [132]:
df5

A         B
Group Number                    
M1    1      -0.229937 -1.283599
      2      -2.711192 -1.522410
      3      -1.416207  1.108544
M2    1       1.131029  0.498600
      2       1.179022  1.322684
      3       1.852155 -0.892172

In [133]:
df5.melt(var_name="Columns", value_name="value", ignore_index=False)

Columns     value
Group Number                  
M1    1            A -0.229937
      2            A -2.711192
      3            A -1.416207
M2    1            A  1.131029
      2            A  1.179022
      3            A  1.852155
M1    1            B -1.283599
      2            B -1.522410
      3            B  1.108544
M2    1            B  0.498600
      2            B  1.322684
      3            B -0.892172

In [134]:
df5.loc["M2"].melt()

variable     value
0        A  1.131029
1        A  1.179022
2        A  1.852155
3        B  0.498600
4        B  1.322684
5        B -0.892172

In [135]:
df5.unstack()

A                             B                    
Number         1         2         3         1         2         3
Group                                                             
M1     -0.229937 -2.711192 -1.416207 -1.283599 -1.522410  1.108544
M2      1.131029  1.179022  1.852155  0.498600  1.322684 -0.892172

In [136]:
df6 = df5.unstack().melt()
df6

NaN  Number     value
0    A       1 -0.229937
1    A       1  1.131029
2    A       2 -2.711192
3    A       2  1.179022
4    A       3 -1.416207
5    A       3  1.852155
6    B       1 -1.283599
7    B       1  0.498600
8    B       2 -1.522410
9    B       2  1.322684
10   B       3  1.108544
11   B       3 -0.892172

In [268]:
pd.DataFrame(df6.stack())

0
0  NaN            A
   Number         1
   value    1.02905
1  NaN            A
   Number         1
   value  -0.662684
2  NaN            A
   Number         2
   value     2.0608
3  NaN            A
   Number         2
   value  -0.260526
4  NaN            A
   Number         3
   value   -2.27374
5  NaN            A
   Number         3
   value   0.164244
6  NaN            B
   Number         1
   value  -0.272079
7  NaN            B
   Number         1
   value   0.420491
8  NaN            B
   Number         2
   value   -1.04687
9  NaN            B
   Number         2
   value    0.38978
10 NaN            B
   Number         3
   value     1.2181
11 NaN            B
   Number         3
   value  -0.371581

In [ ]:
#@title
df6.columns = ["kind",	"Number",	"value"]
df6.pivot_table(values="value", index=["kind"], columns=["Number"],aggfunc=[min,max])

# The End of the Session

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___