___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Series, Session - 3</p><h1>

## Creating a Pandas Series

In [ ]:
#pip install pandas

In [1]:
import numpy as np
import pandas as pd

### Creating a Pandas Series with Basic Format

In [2]:
a = [np.random.randint(0,100) for i in range(5)]
a

[45, 52, 74, 7, 1]

In [3]:
pd.Series(a)

0    45
1    52
2    74
3     7
4     1
dtype: int64

In [4]:
ser = pd.Series(a)

ser

0    45
1    52
2    74
3     7
4     1
dtype: int64

### Basic Attributes of Series

In [5]:
type(ser)

pandas.core.series.Series

In [6]:
ser.dtype

dtype('int64')

In [7]:
ser.size

5

In [8]:
ser.ndim

1

In [11]:
ser.index

RangeIndex(start=0, stop=5, step=1)

In [9]:
ser.values

array([45, 52, 74,  7,  1], dtype=int64)

In [10]:
[print(i) for i in ser.values]

45
52
74
7
1


[None, None, None, None, None]

In [12]:
ser.head(3)

0    45
1    52
2    74
dtype: int64

In [14]:
ser.tail(3)

2    74
3     7
4     1
dtype: int64

### Creating Pandas Series by Using a ``list``, numpy array or ``dict``ionary

In [15]:
labels = ['aron','baron','charon']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'b':20,'c':30}


### **Using Lists**

In [16]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [17]:
pd.Series(data = my_list,index = labels)

aron      10
baron     20
charon    30
dtype: int64

In [18]:
pd.Series(my_list, labels)

aron      10
baron     20
charon    30
dtype: int64

### **Using NumPy Arrays**

In [19]:
arr

array([10, 20, 30])

In [20]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [21]:
pd.Series(arr,labels)

aron      10
baron     20
charon    30
dtype: int32

### **Using Dictionary**

In [22]:
d

{'a': 10, 'b': 20, 'c': 30}

In [23]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [24]:
pd.Series(d,["w","c","d"])

w     NaN
c    30.0
d     NaN
dtype: float64

### Data in a Series

A pandas Series can hold a variety of object types:

In [25]:
labels

['aron', 'baron', 'charon']

In [27]:
pd.Series(data = labels)

0      aron
1     baron
2    charon
dtype: object

In [28]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [29]:
mix_data = [1,"cat",True]

In [30]:
x = np.array(mix_data)
x 

array(['1', 'cat', 'True'], dtype='<U11')

In [31]:
y = pd.Series(mix_data)
y

0       1
1     cat
2    True
dtype: object

In [ ]:
print(type(x[0]))
print(type(y[0]))

<class 'numpy.str_'>
<class 'int'>


## Sorting Index | Sorting Values | Check Data if it is in the pd.Series

### [`.sort_index`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-series-sort_index.ipynb) | [`.sort_values`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-series-sort_values.ipynb) | [`.isin`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-series-isin.ipynb)

***



In [32]:
values = np.random.randint(1,20,9)
labels = [i for i in "clarusway"]

In [33]:
oser = pd.Series(data=values,index=labels)
oser

c     6
l    14
a    12
r    19
u    14
s    10
w    14
a    13
y    15
dtype: int32

In [34]:
oser.sort_index()

a    12
a    13
c     6
l    14
r    19
s    10
u    14
w    14
y    15
dtype: int32

In [35]:
oser.sort_values()

c     6
s    10
a    12
a    13
l    14
u    14
w    14
y    15
r    19
dtype: int32

In [37]:
oser.isin([6])

c     True
l    False
a    False
r    False
u    False
s    False
w    False
a    False
y    False
dtype: bool

In [36]:
oser[oser.isin([6])]

c    6
dtype: int32

In [ ]:
# How can I use .isin() on labels?

In [ ]:
#@title
oser.index.isin(["a"])

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [38]:
ser1 = pd.Series([1,2,3,4,6],index = ['USA', 'Germany','USSR', 'Japan','Turkey'])                                   

In [39]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
Turkey     6
dtype: int64

In [40]:
ser1[0]

1

In [41]:
ser1["USA"]

1

In [42]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])                                   

In [43]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [45]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
Turkey     6
dtype: int64

In [44]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
Turkey     NaN
USA        2.0
USSR       NaN
dtype: float64

In [ ]:
ser1.add(ser2,fill_value=0)

Germany    4.0
Italy      5.0
Japan      8.0
Turkey     6.0
USA        2.0
USSR       3.0
dtype: float64

In [ ]:
# Find the function that we use for subtraction? 

### Indexing Examples

In [46]:
a = np.array([1,2,33,444,75])
panser = pd.Series(a)
panser

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [47]:
panser[0]

1

In [48]:
panser[0:3]

0     1
1     2
2    33
dtype: int32

### pandas_series[index] | pandas_series[[indices, indices...]]

In [49]:
oindex = np.random.choice(["sarah","jack", "müslüm", "ismail", 
             "gizem","ali ihsan","ertuğrul","niyazi",
             "osman ali","baki","kasım","kübra","fatih",
             "said","taner","aslı","sami","ibrahim"],size =6, replace=False)

print(oindex)

['ali ihsan' 'osman ali' 'fatih' 'müslüm' 'ismail' 'sarah']


In [50]:
age = [20,25,27,30,21,29]

In [51]:
panser = pd.Series(data = age, index = oindex)

panser

ali ihsan    20
osman ali    25
fatih        27
müslüm       30
ismail       21
sarah        29
dtype: int64

In [52]:
panser[0]

20

In [53]:
panser["ali ihsan"]

20

In [54]:
panser[["müslüm","ismail"]]

müslüm    30
ismail    21
dtype: int64

In [55]:
panser["müslüm":"ismail"]

müslüm    30
ismail    21
dtype: int64

In [56]:
panser[3:5]

müslüm    30
ismail    21
dtype: int64

In [57]:
panser[[3,4]]

müslüm    30
ismail    21
dtype: int64

### Several Selecting Attributes

In [58]:
panser

ali ihsan    20
osman ali    25
fatih        27
müslüm       30
ismail       21
sarah        29
dtype: int64

In [59]:
panser.index

Index(['ali ihsan', 'osman ali', 'fatih', 'müslüm', 'ismail', 'sarah'], dtype='object')

In [60]:
panser.keys()

Index(['ali ihsan', 'osman ali', 'fatih', 'müslüm', 'ismail', 'sarah'], dtype='object')

In [61]:
panser.values

array([20, 25, 27, 30, 21, 29], dtype=int64)

In [62]:
panser.items()

In [63]:
list(panser.items())

[('ali ihsan', 20),
 ('osman ali', 25),
 ('fatih', 27),
 ('müslüm', 30),
 ('ismail', 21),
 ('sarah', 29)]

In [64]:
dict(panser.items())

{'ali ihsan': 20,
 'osman ali': 25,
 'fatih': 27,
 'müslüm': 30,
 'ismail': 21,
 'sarah': 29}

In [65]:
for index,(label,value) in enumerate(panser.items()):
    print(index, "-",label,"-", value)
    

0 - ali ihsan - 20
1 - osman ali - 25
2 - fatih - 27
3 - müslüm - 30
4 - ismail - 21
5 - sarah - 29


In [66]:
panser

ali ihsan    20
osman ali    25
fatih        27
müslüm       30
ismail       21
sarah        29
dtype: int64

In [67]:
"orion" in panser

False

In [68]:
"sarah" in panser

True

In [69]:
121 in panser.values

False

In [70]:
20 in panser.values

True

In [71]:
panser["sarah"]

29

In [72]:
panser["sarah"] = 18
    
panser

ali ihsan    20
osman ali    25
fatih        27
müslüm       30
ismail       21
sarah        18
dtype: int64

In [73]:
panser > 25 # to find y generation

ali ihsan    False
osman ali    False
fatih         True
müslüm        True
ismail       False
sarah        False
dtype: bool

In [74]:
panser[panser > 25]

fatih     27
müslüm    30
dtype: int64

In [76]:
panser.drop(["fatih", "müslüm"],inplace = True)

In [77]:
panser

ali ihsan    20
osman ali    25
ismail       21
sarah        18
dtype: int64

# The End of the Session - 3

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___