___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">NumPy Lesson, Session - 2 (Part-2) </p><h1>

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [3]:
arr[8]

8

In [4]:
arr[-1]

10

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
#arr[start:stop:step]

In [8]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [9]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [10]:
arr[0:5] = 100


arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
a = [0,  2,  4,  6,  8, 10]

In [13]:
#a[0:3] = 100

TypeError: can only assign an iterable

In [14]:
a[0:3] = [100,100,100]
a

[100, 100, 100, 6, 8, 10]

In [16]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = arr[0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_of_arr[:] = 99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_copy[0:6] = [0,1,2,3,4,5]


In [23]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row,col]</b>. I recommend usually using the comma notation for clarity.</p>

In [25]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d[2]

array([35, 40, 45])

In [33]:
arr_2d[1][1]

25

In [34]:
arr_2d[1,1]

25

In [35]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [39]:
arr_2d[:,1]

array([10, 25, 40])

In [40]:
arr_2d[1,1] = 55

arr_2d

array([[ 5, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [42]:
arr_2d[0,0] = 3.3
arr_2d

array([[ 3, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [43]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [44]:
v[1]

3

In [45]:
v[3]

9

In [46]:
id_list = [1,3,5]
v[id_list]

array([ 3,  9, 15])

In [49]:
# Set up matrix
arr2d = np.zeros((10, 10), dtype=int)

arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:

for i  in range(10):
    arr2d[i] = i
    
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [52]:
arr2d[[2,4,6,8]]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

<h3>any_array[[row indices], [column indices]]</h3>

In [53]:
jj = np.arange(1,17).reshape((4,4))
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
jj[[1,2],[0,3]]

array([ 5, 12])

In [55]:
jj[[0,2,3],[0,1,3]]

array([ 1, 10, 16])

### Using ***basic index*** and ***fancy index*** together

In [56]:
jj[0:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### Using ***basic slicing*** and ***fancy index*** together

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

-``& ==> and``

-``| ==> or``

# NumPy Operations

## Arithmetic Operations

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

## Universal Array Functions

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

## Statistical Calculations

* ``np.mean(arr,axis=0)`` | Returns mean along specific axis

* ``arr.sum()`` | Returns sum of arr

* ``arr.min()`` | Returns minimum value of arr

* ``arr.max(axis=0)`` | Returns maximum value of specific axis

* ``np.var(arr)`` | Returns the variance of array

* ``np.std(arr,axis=1)`` | Returns the standard deviation of specific axis

* ``arr.corrcoef()`` | Returns correlation coefficient of array

# The End of the Session - 2

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.