___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 3</p><h1>
    <h2><p style="text-align: center;">Part - 2</p><h2>

# Data Frames

 - ### ``DataFrames`` are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [2]:
import pandas as pd
import numpy as np

 - ### Creating a DataFrame using the ``list``s of data and columns

In [2]:
data = [1, 2, 39, 67, 90] 

In [3]:
data

[1, 2, 39, 67, 90]

In [5]:
pd.DataFrame(data, columns = ["column_name"])

column_name
0            1
1            2
2           39
3           67
4           90

 - ### Creating a DataFrame using a ``NumPy Arrays``

In [6]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
pd.DataFrame(m,columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [8]:
pd.DataFrame(data = m,columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [9]:
df = pd.DataFrame(data = m,columns = ["var1","var2","var3"])
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [12]:
df.head(2)

var1  var2  var3
0     1     2     3
1     4     5     6

In [14]:
df.tail(1)

var1  var2  var3
2     7     8     9

In [15]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [16]:
df.columns = ["new1","new2","new3"]


In [17]:
df

new1  new2  new3
0     1     2     3
1     4     5     6
2     7     8     9

In [18]:
type(df)

pandas.core.frame.DataFrame

In [19]:
df.shape

(3, 3)

In [20]:
df.ndim

2

In [21]:
df.size

9

In [22]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

 - ### Creating a DataFrame using a ``dict``

In [23]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [24]:
s1

array([4, 6, 6, 0, 0])

In [25]:
s2

array([0, 6, 9, 5, 6])

In [26]:
s3

array([4, 2, 4, 0, 7])

In [27]:
myDict = {"var1":s1,"var2":s2,"var3":s3}
myDict

{'var1': array([4, 6, 6, 0, 0]),
 'var2': array([0, 6, 9, 5, 6]),
 'var3': array([4, 2, 4, 0, 7])}

In [28]:
df1 = pd.DataFrame(myDict)
df1

var1  var2  var3
0     4     0     4
1     6     6     2
2     6     9     4
3     0     5     0
4     0     6     7

In [29]:
df1[1:3]

var1  var2  var3
1     6     6     2
2     6     9     4

In [30]:
df1.index = ["a","b","c","d","e"]

In [31]:
df1

var1  var2  var3
a     4     0     4
b     6     6     2
c     6     9     4
d     0     5     0
e     0     6     7

In [32]:
df1[1:4]

var1  var2  var3
b     6     6     2
c     6     9     4
d     0     5     0

In [34]:
df1["b":"d"]

var1  var2  var3
b     6     6     2
c     6     9     4
d     0     5     0

In [35]:
"var2" in df1

True

In [36]:
"martin" in df1

False

In [37]:
2 in df1.values

True

### Now, let's examine again the ***indexing, selection*** and ***slicing*** methods and several ***attributes*** using a different DataFrame

In [3]:
import numpy as np
import pandas as pd

In [6]:
df3 = pd.DataFrame(np.random.randn(5,4),index = 'A B C D E'.split(), columns = 'W X Y Z'.split())

df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786
E -0.547876  0.565483 -0.189934 -0.362493

In [7]:
df3['W']

A   -0.804236
B    1.599428
C    0.337456
D    0.654977
E   -0.547876
Name: W, dtype: float64

In [8]:
type(df3['W'])

pandas.core.series.Series

In [9]:
df3[['W']]

W
A -0.804236
B  1.599428
C  0.337456
D  0.654977
E -0.547876

In [10]:
type(df3[['W']])

pandas.core.frame.DataFrame

In [11]:
df3[['W','Z']]

W         Z
A -0.804236 -1.408980
B  1.599428  1.236204
C  0.337456 -1.631085
D  0.654977 -0.971786
E -0.547876 -0.362493

In [12]:
df3.W

A   -0.804236
B    1.599428
C    0.337456
D    0.654977
E   -0.547876
Name: W, dtype: float64

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [13]:
df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786
E -0.547876  0.565483 -0.189934 -0.362493

In [14]:
df3["A" : "C"]

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085

In [16]:
df3["A" : "A"]

W         X         Y        Z
A -0.804236 -0.600027  0.360768 -1.40898

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 4</p><h1>
    <h2><p style="text-align: center;">Part - 1</p><h2>

**Creating a new column:**

In [17]:
df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786
E -0.547876  0.565483 -0.189934 -0.362493

In [18]:
df3["new"] = df3['W'] + df3['Y']

df3

W         X         Y         Z       new
A -0.804236 -0.600027  0.360768 -1.408980 -0.443468
B  1.599428  2.157681 -1.568512  1.236204  0.030915
C  0.337456  0.385329 -0.525885 -1.631085 -0.188428
D  0.654977  0.138792  0.544640 -0.971786  1.199617
E -0.547876  0.565483 -0.189934 -0.362493 -0.737810

### [Removing Columns & Rows](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-drop.ipynb)

 - ### Removing Columns

In [19]:
df3.drop('new', axis = 1)

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786
E -0.547876  0.565483 -0.189934 -0.362493

In [20]:
df3

W         X         Y         Z       new
A -0.804236 -0.600027  0.360768 -1.408980 -0.443468
B  1.599428  2.157681 -1.568512  1.236204  0.030915
C  0.337456  0.385329 -0.525885 -1.631085 -0.188428
D  0.654977  0.138792  0.544640 -0.971786  1.199617
E -0.547876  0.565483 -0.189934 -0.362493 -0.737810

In [21]:
df3.drop('new', axis = 1, inplace = True)

In [22]:
df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786
E -0.547876  0.565483 -0.189934 -0.362493

 - ### Removing rows

In [23]:
df3.drop('E',axis = 0)

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786

In [24]:
df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786
E -0.547876  0.565483 -0.189934 -0.362493

In [25]:
df3.drop('E',axis = 0,inplace = True)

In [26]:
df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786

### Selecting Rows

- ### First, let's take a quick look at [`.loc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-loc.ipynb) | [`.iloc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-iloc.ipynb)

#### `.loc[]` → allows us to select data using **labels** (names) of rows (index) & columns

#### `.iloc[]` → allows us to select data using **index numbers** of rows (index) & columns. it's like classical indexing logic

In [27]:
m = np.random.randint(1,30, size = (10,3))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df4

var1  var2  var3
0    12    11     7
1     4     1    12
2     7    10     6
3     7    27    27
4     8     3    24
5     2     9     2
6    13     8    11
7    28    21    16
8    28    25    28
9    13    10     8

In [28]:
df4.loc[1]

var1     4
var2     1
var3    12
Name: 1, dtype: int64

In [30]:
df4.loc[1:4]

var1  var2  var3
1     4     1    12
2     7    10     6
3     7    27    27
4     8     3    24

In [31]:
df4.iloc[1:4]

var1  var2  var3
1     4     1    12
2     7    10     6
3     7    27    27

In [32]:
df4.index = "a b c d e f g h i j".split()

In [33]:
df4

var1  var2  var3
a    12    11     7
b     4     1    12
c     7    10     6
d     7    27    27
e     8     3    24
f     2     9     2
g    13     8    11
h    28    21    16
i    28    25    28
j    13    10     8

In [34]:
df4.iloc[1:4]

var1  var2  var3
b     4     1    12
c     7    10     6
d     7    27    27

In [36]:
#df4.loc[1:4]

In [37]:
df4.loc["a" : "d"]

var1  var2  var3
a    12    11     7
b     4     1    12
c     7    10     6
d     7    27    27

In [38]:
df4

var1  var2  var3
a    12    11     7
b     4     1    12
c     7    10     6
d     7    27    27
e     8     3    24
f     2     9     2
g    13     8    11
h    28    21    16
i    28    25    28
j    13    10     8

In [39]:
df4.loc["b","var2"]

1

In [40]:
df4.iloc[1,1]

1

In [42]:
df4.loc["c":"f","var2"]

c    10
d    27
e     3
f     9
Name: var2, dtype: int64

In [43]:
df4["var2"][2:6]

c    10
d    27
e     3
f     9
Name: var2, dtype: int64

In [45]:
df4.iloc[2:6,1]

c    10
d    27
e     3
f     9
Name: var2, dtype: int64

In [46]:
df4.var2[2:6]

c    10
d    27
e     3
f     9
Name: var2, dtype: int64

In [49]:
df4.loc["c":"f"][["var2"]]

var2
c    10
d    27
e     3
f     9

In [50]:
type(df4.loc["c":"f"][["var2"]])

pandas.core.frame.DataFrame

#### Let's continue to examine `.loc[]` and `.iloc[]` using ``df3`` again

In [51]:
df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786

In [52]:
df3.iloc[2]

W    0.337456
X    0.385329
Y   -0.525885
Z   -1.631085
Name: C, dtype: float64

In [53]:
df3.iloc[[2]]

W         X         Y         Z
C  0.337456  0.385329 -0.525885 -1.631085

### Selecting subset of rows and columns

 - ### `.loc[[row labels|names], [column labels|names]]`

 - ### `.iloc[[row index numbers], [column index numbers]]`

In [54]:
df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786

In [55]:
df3.loc["B","Y"]

-1.5685124601698675

In [56]:
df3.loc[["B"],["Y"]]

Y
B -1.568512

In [63]:
df3.loc[["A","B"],["W","X"]]

W         X
A -0.804236 -0.600027
B  1.599428  2.157681

In [61]:
df3.iloc[0:2,0:2]

W         X
A -0.804236 -0.600027
B  1.599428  2.157681

In [60]:
type(df3.iloc[0:2,0:2])

pandas.core.frame.DataFrame

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [64]:
df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786

In [65]:
df3 > 0

W      X      Y      Z
A  False  False   True  False
B   True   True  False   True
C   True   True  False  False
D   True   True   True  False

In [66]:
df3[df3 > 0]

W         X         Y         Z
A       NaN       NaN  0.360768       NaN
B  1.599428  2.157681       NaN  1.236204
C  0.337456  0.385329       NaN       NaN
D  0.654977  0.138792  0.544640       NaN

In [67]:
df3[df3["W"] > 0]

W         X         Y         Z
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786

In [69]:
df3[df3["W"] > 0]["W"]

B    1.599428
C    0.337456
D    0.654977
Name: W, dtype: float64

In [70]:
type(df3[df3["W"] > 0]["W"])

pandas.core.series.Series

In [71]:
df3[df3["W"] > 0][["W"]]

W
B  1.599428
C  0.337456
D  0.654977

In [72]:
df3[df3["W"] > 0][["Y","X"]]

Y         X
B -1.568512  2.157681
C -0.525885  0.385329
D  0.544640  0.138792

#### For two conditions you can use **|** → `or`,  **&** →  `and` with parenthesis:

In [73]:
df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786

In [74]:
df3[(df3['W'] > 0) & (df3['Y'] > 1)]

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

#### Conditional selection using ``.loc[]`` and ``.iloc[]``

In [75]:
df3[(df3['W'] > 0) | (df3['Y'] > 1)]

W         X         Y         Z
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786

In [78]:
df3.loc[(df3.X > 0),["X","Z"]]

X         Z
B  2.157681  1.236204
C  0.385329 -1.631085
D  0.138792 -0.971786

# ------Conditional Filtering-----


### Link to [Conditional Filtering Notebook](02-Conditional-Filtering.ipynb)


___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 5</p><h1>

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [79]:
df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786

In [80]:
df3.reset_index()

index         W         X         Y         Z
0     A -0.804236 -0.600027  0.360768 -1.408980
1     B  1.599428  2.157681 -1.568512  1.236204
2     C  0.337456  0.385329 -0.525885 -1.631085
3     D  0.654977  0.138792  0.544640 -0.971786

In [81]:
df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786

In [82]:
df3.reset_index(drop = True)

W         X         Y         Z
0 -0.804236 -0.600027  0.360768 -1.408980
1  1.599428  2.157681 -1.568512  1.236204
2  0.337456  0.385329 -0.525885 -1.631085
3  0.654977  0.138792  0.544640 -0.971786

In [83]:
df3

W         X         Y         Z
A -0.804236 -0.600027  0.360768 -1.408980
B  1.599428  2.157681 -1.568512  1.236204
C  0.337456  0.385329 -0.525885 -1.631085
D  0.654977  0.138792  0.544640 -0.971786

In [84]:
df3.reset_index(drop = True,inplace = True)

In [85]:
df3

W         X         Y         Z
0 -0.804236 -0.600027  0.360768 -1.408980
1  1.599428  2.157681 -1.568512  1.236204
2  0.337456  0.385329 -0.525885 -1.631085
3  0.654977  0.138792  0.544640 -0.971786

In [88]:
newindx = 'CA NY WY OR'.split()

In [89]:
df3["States"] = newindx

In [90]:
df3

W         X         Y         Z States
0 -0.804236 -0.600027  0.360768 -1.408980     CA
1  1.599428  2.157681 -1.568512  1.236204     NY
2  0.337456  0.385329 -0.525885 -1.631085     WY
3  0.654977  0.138792  0.544640 -0.971786     OR

In [91]:
df3.set_index('States')

W         X         Y         Z
States                                        
CA     -0.804236 -0.600027  0.360768 -1.408980
NY      1.599428  2.157681 -1.568512  1.236204
WY      0.337456  0.385329 -0.525885 -1.631085
OR      0.654977  0.138792  0.544640 -0.971786

In [92]:
df3

W         X         Y         Z States
0 -0.804236 -0.600027  0.360768 -1.408980     CA
1  1.599428  2.157681 -1.568512  1.236204     NY
2  0.337456  0.385329 -0.525885 -1.631085     WY
3  0.654977  0.138792  0.544640 -0.971786     OR

In [93]:
df3.set_index('States', inplace = True)

In [94]:
df3

W         X         Y         Z
States                                        
CA     -0.804236 -0.600027  0.360768 -1.408980
NY      1.599428  2.157681 -1.568512  1.236204
WY      0.337456  0.385329 -0.525885 -1.631085
OR      0.654977  0.138792  0.544640 -0.971786

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [95]:
# Index Levels
outside = ['M1', 'M1', 'M1', 'M2', 'M2', 'M2']
inside = [1, 2, 3, 1, 2, 3]
multi_index = list(zip(outside, inside))
multi_index

[('M1', 1), ('M1', 2), ('M1', 3), ('M2', 1), ('M2', 2), ('M2', 3)]

In [97]:
hier_index = pd.MultiIndex.from_tuples(multi_index)
hier_index

MultiIndex([('M1', 1),
            ('M1', 2),
            ('M1', 3),
            ('M2', 1),
            ('M2', 2),
            ('M2', 3)],
           )

In [98]:
df5 = pd.DataFrame(np.random.randn(6,2),index = hier_index, columns = ["A","B"])

df5

A         B
M1 1  0.198507  0.217724
   2 -0.430647 -2.269375
   3  0.113226  0.175148
M2 1  0.277431 -1.262438
   2  0.582924 -0.759903
   3  0.223767  0.853332

In [99]:
df5.loc["M1"]

A         B
1  0.198507  0.217724
2 -0.430647 -2.269375
3  0.113226  0.175148

In [100]:
df5.loc["M1"].loc[1]

A    0.198507
B    0.217724
Name: 1, dtype: float64

In [103]:
df5.index.names = ['Group','Number']

In [104]:
df5

A         B
Group Number                    
M1    1       0.198507  0.217724
      2      -0.430647 -2.269375
      3       0.113226  0.175148
M2    1       0.277431 -1.262438
      2       0.582924 -0.759903
      3       0.223767  0.853332

### let's take a quick look at the [``.xs()``](http://localhost:8888/notebooks/w3resource-pandas-dataframe-xs.ipynb)

In [105]:
df5.xs('M1')

A         B
Number                    
1       0.198507  0.217724
2      -0.430647 -2.269375
3       0.113226  0.175148

In [106]:
df5.xs('M2')

A         B
Number                    
1       0.277431 -1.262438
2       0.582924 -0.759903
3       0.223767  0.853332

In [107]:
df5.xs(["M1",1])

A    0.198507
B    0.217724
Name: (M1, 1), dtype: float64

In [108]:
df5.xs(("M1",1))

A    0.198507
B    0.217724
Name: (M1, 1), dtype: float64

In [112]:
df5.xs(("M1",1),level = [0,1])

A         B
Group Number                    
M1    1       0.198507  0.217724

In [115]:
df5

A         B
Group Number                    
M1    1       0.198507  0.217724
      2      -0.430647 -2.269375
      3       0.113226  0.175148
M2    1       0.277431 -1.262438
      2       0.582924 -0.759903
      3       0.223767  0.853332

In [114]:
df5.xs(1,level = "Number")

A         B
Group                    
M1     0.198507  0.217724
M2     0.277431 -1.262438

In [116]:
df5.xs(1,level = 1 )

A         B
Group                    
M1     0.198507  0.217724
M2     0.277431 -1.262438

### [Removing Columns & Rows](http://localhost:8888/notebooks/w3resource-pandas-dataframe-drop.ipynb) from Multi-Index DataFrame

# The End of the Session